### ISSUE TITLE
Metro has encountered an error: resolveDependencies: Found duplicate dependency key 'undefined'

### ISSUE THREAD

**Issue by baselshlewett** [Mindinventory/rn-top-navbar#1]
![Screenshot 2023-07-08 at 1 14 44](https://github.com/Mindinventory/React-Native-top-navbar/assets/20260587/28555f13-c953-4c49-8393-ed1a119bbd4f)

Unable to run on either Android nor iOS with above error.

Steps to make sure this is the faulty library:
1) Start bare-bone react and make sure it builds correctly
2) Add libraries until encountering above error
...

**Comment by chiragramimi** [comment]
@baselshlewett.  We have fixed this issue in the latest build, version 0.0.4. We eliminated an additional dependency that was causing conflicts with others. To resolve this, kindly delete the existing node_modules and proceed to install the updated version.
